### ISSUE TITLE
Config entry from integration weatherflow_forecast has an invalid unique_id of type int

### ISSUE THREAD

**Issue by dhover** [briis/weatherflow_forecast#199]
**Describe the bug**

Error in logfile:
```
2024-12-01 14:11:10.081 ERROR (MainThread) [homeassistant.config_entries] Config entry 'xxx' from integration weatherflow_forecast has an invalid unique_id '12345' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
```
**To Reproduce**
Restart integration
 
**Expected behavior**
No errors

**Comment by StarGateGit** [comment]
It seems to have lost some entities
![Screenshot_20241207_065628](https://github.com/user-attachments/assets/97369c8f-d8a7-46cf-a2ee-a218d215dbb7)
I did edit all the not available ones out...sorry, I didn't make a note of what changed!

**Comment by mstovenour** [comment]
I also had this message during initial startup when installing WeatherFlow on a new home assistant supervised installation:

```
2024-12-23 10:40:15.042 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of pyweatherflow-forecast==1.1.0
2024-12-23 10:42:21.092 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Rottino Dr' from integration weatherflow_forecast has an invalid unique_id '146439' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
2024-12-23 10:42:21.092 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Rottino Dr' from integration weatherflow_forecast has an invalid unique_id '146439' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
```

**Comment by Erik-MG** [comment]
After updating 1.0.12 I'm still getting the same error message:
`
2025-01-09 13:27:17.513 ERROR (MainThread) [homeassistant.config_entries] Config entry 'B1-tmpst-2' from integration weatherflow_forecast has an invalid unique_id '135295' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
` 

I'm running Home Assistant 2024.12.5 in a Docker container, HACS 2.0.1 and Weatherflow integration 1.0.12.

**Comment by briis** [comment]
When setting up your station from scratch, I don't get this error.
My best assumption is that, even though you upgraded to the latest version, the Station ID is still stored as an Integer, and not a string.
Unless you have modified a lot of sensor names, please try and delete your station, and make a new installation, and let me know if you still see the error.

**Comment by daviddesmet** [comment]
Is this something we can update at the DB level or something without deleting and creating a new station?

**Comment by briis** [comment]
Have you updated to 1.0.13?
It should finally be fixed in that release

**Comment by daviddesmet** [comment]
Yes, I'm on 1.0.13 and I've just rebooted the HA server and still get the log message when it boots:

```log
2025-01-16 15:21:08.053 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Home' from integration weatherflow_forecast has an invalid unique_id 'xxx' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
```

**Comment by Erik-MG** [comment]
I just updated Weatherflow integration to 1.0.13 and I can confirm I also still get the 'invalid unique_id' error message.

I'm hesitant to delete the station and re-create it again. The station name is also linked to my Weatherflow company account. There is also a risk of ending up with lots of duplicate entities which I have to correct manually. Will I loose the link to my history  on influxdb?

**Comment by mwareman** [comment]
Seeing this on my instance as well while troubleshooting Home Assistant crashing/restarting. I don't think the root cause is this integration yet - but I did come across it. 
Everything 100% up to date non-beta.

**Comment by borski** [comment]
This is happening to me as well.

**Comment by StarGateGit** [comment]
Make sure to input the 
Station ID  1****7 
and create a new key.
Had some trouble doing this recently but all seems okay!

**Comment by Pseudophryne** [comment]
@briis I have this issue, weirdly it isn't consistent as the same station with different API has no errors in my test system.

Prod setup
Installation method = Home Assistant OS
Core = 2025.6.3
Supervisor = 2025.06.2
Operating System = 15.2
Frontend = 20250531.4

````
2025-06-27 10:14:55.964 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Ferris St' from integration weatherflow_forecast has an invalid unique_id '6***8' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
2025-06-27 10:14:59.262 INFO (MainThread) [custom_components.weatherflow_forecast] 
-------------------------------------------------------------------
Weatherflow Forecast
Version: 1.0.13
ID: 6***8
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/briis/weatherflow_forecast/issues
Pleae make sure to supply enough debugging information
-------------------------------------------------------------------
````

cheers Simon

**Comment by Pseudophryne** [comment]
> Hi Simon, The fastes fix, is to remove the integration and re-add your station. Alle new stations will created as a string, which is what is required.

Legend
